### ISSUE TITLE
Conflict with other CLI options

### ISSUE THREAD

**Issue by Djaler** [mradionov/eslint-plugin-disable#22]
I build vue project using `vue-cli-service build --modern` command. Looks like it invoke eslint under the hood.

```
[eslint-plugin-disable] Error: Invalid option '--modern' - perhaps you meant '--color'?
    at getOption (/home/smsbulk/workspace/sow/any_branch/frontend/node_modules/optionator/lib/index.js:169:15)
    at Object.parse (/home/smsbulk/workspace/sow/any_branch/frontend/node_modules/optionator/lib/index.js:398:23)
    at Object.<anonymous> (/home/smsbulk/workspace/sow/any_branch/frontend/node_modules/eslint-plugin-disable/index.js:69:29)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Plugins.load (/home/smsbulk/workspace/sow/any_branch/frontend/node_modules/eslint/lib/config/plugins.js:99:26)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (/home/smsbulk/workspace/sow/any_branch/frontend/node_modules/eslint/lib/config/plugins.js:165:21)
    at loadFromDisk (/home/smsbulk/workspace/sow/any_branch/frontend/node_modules/eslint/lib/config/config-file.js:506:35)
    at load (/home/smsbulk/workspace/sow/any_branch/frontend/node_modules/eslint/lib/config/config-file.js:564:20)
    at configExtends.reduceRight (/home/smsbulk/workspace/sow/any_branch/frontend/node_modules/eslint/lib/config/config-file.js:430:36)
```

**Comment by mradionov** [comment]
Thanks, I'll take a look

**Comment by mradionov** [comment]
I've installed the latest Vue CLI, created an empty project with default preset and executed build with `--modern` flag and got no errors.

```bash
$ npm install @vue/cli

$ npx vue create test-project
# ? Please pick a preset: default (babel, eslint)

$ cd test-project

$ npx vue-cli-service build --modern
#  DONE  Build complete. The dist directory is ready to be deployed.
```

I need to somehow reproduce you env because there might be something else using my plugin. Could you please share with me your package.json and maybe .eslitrc config?

**Comment by Djaler** [comment]
I have no access to this project until tomorrow. But I think you should look at this: https://cli.vuejs.org/config/#lintonsave

**Comment by Djaler** [comment]
I create a sample project for you - https://github.com/Djaler/eslint-plugin-disable-bug-sample
Steps to reproduce:
1. `npm install`
2. `npm run build`
3. You will see warning in output

P.S. Yoo will need to do `rm -rf node_modules/.cache/eslint-loader` after each try because of cache.

**Comment by mradionov** [comment]
Thank you very much for the repo, I can see the error now.

**Comment by mradionov** [comment]
`@vue/cli-service` has a `@vue/cli-plugin-eslint` a dependency. It uses ESLint Node.js API to configure and run ESLint which is a problem for me because I use it as well and there is no way to hook up to it from outside and retrieve final ESLint config that will be used for linting files or CLI arguments that are passed to the engine.

When developing a plugin my assumption was that ESLint always runs from CLI and I would use CLI process args and pass them to ESLint engine as is, but looks like it is not always the case and some packages use ESLint Node.js API. Hence I will have to check the type of binary and either use or ignore CLI args.

This brings the second issue that I still need CLI args so my plugin can be configured to process files with different extensions (like `.vue`, `.ts`, etc) and other CLI options like `--fix`. The only option I can think of is to allow end user pass CLI args to my plugin using plugin settings in ESLint config.

```json
"eslintConfig": {
  "eslint-plugin-disable": {
    "cliArgs": ["--ext", ".vue,.ts,.js", "--fix"]
  }
}
```
It is not user-friendly but allows independent configuration of the plugin. Maybe I will find some way of generating correct default args so the user won't have to manually fill up cliArgs all the time. For example if I find that there is a `eslint-plugin-vue` installed, I would default to `--ext .vue`.

**Comment by mradionov** [comment]
Both my plugin and `eslint-plugin-vue` register a processor for files with `.vue` extension and for some reason ESLint only picks first preprocessor from all plugins ( https://github.com/eslint/eslint/blob/master/lib/cli-engine.js#L189 ). This way only one of the plugins will process the files, the other one will be dropped. Reordering plugins in config does not help in this case.

Very tricky situation because we both use ESLint Node.js API directly and there is no place to intercept and inject custom code. I don't want to add any vue-specific code to fix the issue (if it is even possible), because there always will be another new tools which does the same and the number of specific fixes will only grow. Need to think of alternatives.

**Comment by Djaler** [comment]
What about feature request to eslint?

**Comment by mradionov** [comment]
It is one of the options if I run out of ideas, especially that there is one [RFC scheduled for processors](https://github.com/eslint/rfcs/tree/master/designs/2018-processors-improvements).

**Comment by mradionov** [comment]
ESLint issue about improving processors API https://github.com/eslint/eslint/issues/11035

**Comment by mradionov** [comment]
One possible workaround which is not tied to specific plugins is to run my processor first and then run next plugin processor on my results similar ESLint. I will have to manually load all plugins, pick first one with the same file extension and run it's processor.
It will only work when my plugin is first in the list of plugins in ESLint config. Basically I am bypassing ESLint logic which allows to run only one processor (which will be my plugin) and then I run next plugin by myself.
Seems like it will work until new processor API is implemented. All these fixes bring a lot of very specific settings to my plugin, but I guess it is better than nothing :) For a regular ESLint setup nothing will change, these settings will be required for vue-like CLI services which wrap ESLint.

Here is a list of rules to make it work with vue-cli-services for now:

1. `eslint-plugin-disable` settings must be specified in `root` ESLint config file
2. `eslint-plugin-disable` settings must include `"cliArgs"` property with `["--ext", ".js,.vue"]` value to work with Vue files. 
2.1. `["--fix"]` should be added as well if you want files to be autofixed
3. `eslint-plugin-disable` must be first in the `plugins` ESLint config property.

I will continue working following this plan, hope I won't get stuck on anything else.

**Comment by mradionov** [comment]
New release [1.0.4](https://github.com/mradionov/eslint-plugin-disable/releases/tag/v1.0.4) is available.

The plugin should now work along with vue-cli. If we take your sample project that you've created to reproduce the issue, you just have to add the following settings in ESLint config file:

```
// package.json

""eslintConfig": {
    ...,

    "settings": {
      "eslint-plugin-disable": {
        "cliArgs": ["--ext", ".js,.vue"]
      }
    }
}
```

My solution is not ideal, but should work with other CLI services as well. Let me know if it does not work for you or you have any other issues.
Plugin should be working as before if ESLint is used in standalone mode (not in CLI tools).
