### ISSUE TITLE
Feature request: disable only specific rules instead of entire plugin

### ISSUE THREAD

**Issue by nwalters512** [mradionov/eslint-plugin-disable#7]
I'm not sure if this fits within your larger vision of your plugin, but I'd like the ability to only disable specific rules, not entire plugins, in certain directories.

My use case: I have a project that uses ESLint for linting and Jest for unit tests. My tests all live inside directories called `__tests__` that are adjacent to the modules they test. I use `eslint-plugin-import` to lint my import statements. In general, I want to utilize the `import/no-extraneous-dependencies` rule to prevent importing dev dependencies in my application code. However, I do want to be able to import dev dependencies from within my unit tests without the linter complaining. Ideally, I'd be able to do something like the following:

```json
{
  "settings": {
    "eslint-plugin-disable": {
      "paths": {
        "import/no-extraneous-dependencies": ["**/__tests__/**/*.js"]
      }
    }
  }
}
```

That way, other rules from `import` would still run in my `__tests__` directories, and all `import` rules would run for all non-test files.

I'd be willing to do some of the implementation work myself and submit a PR, I just wanted to see if this would be a desired addition to `eslint-plugin-disable` before I put in the work.

**Comment by mradionov** [comment]
Sorry, I am on vacation, I'll be able to review it in 10 days. Thanks!

**Comment by mradionov** [comment]
It is possible to achieve using nested config files - [see section in docs](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy)

Basically, you have your root ESLint config file, where `import/no-extraneous-dependencies` is enabled. 
In your tests directory you should create one more ESLint config, where this rule will be disabled. ESLint won't raise warning for this rule for files in tests directory.

```
.
|-- src
    |-- file1.js
    |-- file2.js
|-- test
    |-- file1.test.js
    |-- file2.test.js
    |-- .eslintrc             <-- nested, rule disabled only for tests
|-- .eslintrc                 <-- root, rule enabled for all code
```

As it is possible to do using ESLint itself, it is well supported and documented, I believe it's better to use official API.

**Comment by nwalters512** [comment]
I was hoping to avoid nested config files; that would require copying a config file into each test directory I have, adding that file to any new test directory, and updating all of them whenever I make a change in order to keep them all in sync. That's why I'd like the ability to use glob matching to specify which directories should have those plugins disabled: I specify it once, and it will work automatically for the lifetime of the project.

**Comment by mradionov** [comment]
To be honest I don't want to bring extra complexity to this plugin by adding support for individual rules, because ESLint itself originally works with rules, it has mechanisms for extending and nesting rules, it also allows to use inline comments to control the rules - it will be very difficult to take care of everything ESLint does in order to make this plugin provide correct results. Yes, you have a pretty simple case with one rule that should be disabled for one or two directories, but later on somebody else will have nested/extended configs and inline comments, and it will be too difficult to handle it from plugin's perspective. It is way much easier to shut down the whole plugin than start dealing with individual rules.

Because of that and because ESLint already provides a way to disable particular rules for directories, even though it might be not the most convenient way for you project, I prefer not to and this feature to the plugin. Thank you for you suggestion though, I really appreciate it.
